load("./get auxiliary data/dates_elections_spain.rda")
load("./get auxiliary data/cod_INE_mun.rda")
source("./utils.R")

library(dplyr)
library(stringr)
library(glue)
library(readr)
library(httr)
library(lubridate)
library(tidyverse)
