load("./get auxiliary data/dates_elections_spain.rda")
load("./get auxiliary data/cod_INE_mun.rda")
load("./get auxiliary data/seat_distribution_congress.rda")
load("./get auxiliary data/seat_distribution_congress.rda")
source("./utils.R")
source("./functions/get_election_dataV2.R")
source("./functions/use_election_data.R")
source("./functions/get_survey_dataV2.R")

library(dplyr)
library(stringr)
library(glue)
library(readr)
library(httr)
library(lubridate)
library(tidyverse)
library(stringdist)
library(stringi)
library(dplyr)
library(ggparliament)
library(ggplot2)
library(dplyr)
library(mapSpain)
library(tidyverse)

