project:
  type: book

book:
  title: "testing quarto book"
  author: "Norah Jones"
  date: "8/25/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd
  cover-image: pollspain_icon.png

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

