---
bibliography: references.bib
csl: apa-6th-edition.csl
---
# Package Overview {.unnumbered}

`pollspain` offers a range of features for its users to work with Spanish electoral data. Primarily, the centralization of official electoral data from the Spanish Ministry of the Interior through [Infoelectoral](https://infoelectoral.interior.gob.es/es/elecciones-celebradas/area-de-descargas/) [@interior2024] through its download, processing and hosting in [Pollspain-data](https://github.com/mikadsr/Pollspain-data) [@pollspain2024]the data repository for the package. This makes it so comprehensive datasets on municipal census information, candidacies, candidates, polling stations, and CERA data from 1982 until 2023 are available through the package.

In addition to this, the package also provides ready-made functions for summarizing and visualizing the information. These functions are designed to be intuitive and easy to use, enabling users to quickly generate insights from the data without requiring extensive programming knowledge.

Lastly, a key feature of the package is the access to electoral survey data. This allows users to access a collection of public opinion polling results and perform analysis such as polling error and house effects on them.

Overall, `pollspain` combines data sourcing, processing and analysis into a single package that empowers users to engage deeply with Spanish electoral data.
